name: Build,Test and Deploy React Application 
on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]
    
jobs:
  build_test:
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci and test
        run: |
            npm ci
            npm test  
        
      - name: Set env
        run: |
            npm i -g semver
            echo "GITHUB_VERSION_BUILD=$(echo $(semver 0.1.1 -i prerelease --preid ${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}))" >> $GITHUB_ENV
      - name: Update versionning
        run: |
            git config --global user.email "balkassechaima8@gmail.com"
            git config --global user.name "chaimaa balkasse"
            npm version ${{env.GITHUB_VERSION_BUILD}}
            echo ${{env.GITHUB_VERSION_BUILD}} >> README.md
            git commit -a -m "new version ${{env.GITHUB_VERSION_BUILD}}"
      - name: Build and docs
        run: |
            npm run jsdoc
            npm run build --if-present
      - name: Push changes
        run: git push
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
            name: build-artifact
            path: build
  #Deploy job
  deploy:
       # Deploy to thr github-pages environment
       environment:
         name: github-pages
         url: ${{steps.deployment.outputs.page_url}}
       runs-on: ubuntu-latest
       # grant GITHUB_TOKEN the permissions required to make a Page deployment
       permissions:
         pages: write
         id-token: write
       needs: build_test
       steps:
        # - name: Download artifact
        #   uses: actions/download-artifact@v2
        #   with:
        #     name: build-artifact
        #     path: build
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v2


      
      
      
